"""AI story analyzer — analyzes work items before implementation."""

from __future__ import annotations

import json
import logging
import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

import openai

logger = logging.getLogger("devops_ai_agent.analyzer")

_TEMPLATE_PATH = Path(__file__).parent.parent.parent / "templates" / "analyze.md"


@dataclass
class AnalysisResult:
    """Structured result from AI story analysis."""

    summary: str = ""
    requires_code_change: bool = True
    confidence: str = "medium"
    affected_areas: list[str] = field(default_factory=list)
    approach: str = ""
    risks: list[str] = field(default_factory=list)
    questions: list[str] = field(default_factory=list)
    estimated_complexity: str = "moderate"
    recommendation: str = ""
    raw_response: str = ""

    def to_markdown(self) -> str:
        """Format the analysis as a markdown comment for Azure DevOps / Zendesk."""
        code_label = "Yes" if self.requires_code_change else "No"
        areas = ", ".join(self.affected_areas) if self.affected_areas else "N/A"
        risks = "\n".join(f"- {r}" for r in self.risks) if self.risks else "- None identified"
        questions = "\n".join(f"- {q}" for q in self.questions) if self.questions else "- None"

        return (
            f"## 🤖 AI Story Analysis\n\n"
            f"**Summary:** {self.summary}\n\n"
            f"| Attribute | Value |\n"
            f"|-----------|-------|\n"
            f"| Code change required | {code_label} |\n"
            f"| Confidence | {self.confidence} |\n"
            f"| Complexity | {self.estimated_complexity} |\n"
            f"| Affected areas | {areas} |\n\n"
            f"### Approach\n{self.approach}\n\n"
            f"### Risks\n{risks}\n\n"
            f"### Open Questions\n{questions}\n\n"
            f"### Recommendation\n{self.recommendation}\n\n"
            f"---\n*Generated by DevOps AI Agent*"
        )


class StoryAnalyzer:
    """Analyzes stories/tickets using AI to determine next steps."""

    def __init__(self, config: dict):
        self.config = config
        ai = config.get("ai_agent", {})
        self.provider = ai.get("provider", "copilot")
        self.model = ai.get("model", "gpt-4o")
        self.max_tokens = ai.get("max_tokens", 4096)
        self.temperature = ai.get("temperature", 0.2)
        self.story_id: int | None = None  # Set by pipeline before calling analyze()

    def _record_usage(self, response, stage: str) -> None:
        """Record token usage from an API response."""
        try:
            from src.history import save_token_usage
            usage = getattr(response, "usage", None)
            if not usage:
                return
            prompt = getattr(usage, "prompt_tokens", 0) or getattr(usage, "input_tokens", 0) or 0
            completion = getattr(usage, "completion_tokens", 0) or getattr(usage, "output_tokens", 0) or 0
            save_token_usage(
                story_id=self.story_id, stage=stage, provider=self.provider,
                model=self.model, prompt_tokens=prompt, completion_tokens=completion,
            )
        except Exception as e:
            logger.debug("Failed to record token usage: %s", e)

    def analyze(self, story_context: str, module_summary: str = "") -> AnalysisResult:
        """Analyze a story and return structured findings.

        Strategy: fetch URLs → Python heuristic → Claude CLI (Team plan) → API (fallback).
        """
        # Step 1: Fetch URLs referenced in the story (pure Python, free).
        # Done FIRST so heuristic and Claude CLI both get enriched context.
        url_context = self._extract_and_fetch_urls(story_context)
        if url_context:
            story_context = story_context + "\n\n" + url_context
            logger.info("Enriched story context with URL content (%d chars added).", len(url_context))
        else:
            logger.info("No URL content fetched (0 fetchable URLs or all failed).")

        # Step 2: Python heuristic — catch obvious non-code stories for free.
        heuristic = self._python_heuristic(story_context)
        if heuristic is not None:
            logger.info("Python heuristic resolved analysis — no AI call needed.")
            return heuristic

        # Step 2: Claude Code CLI — uses Team plan, zero API cost.
        cli_result = self._try_claude_cli(story_context, module_summary)
        if cli_result is not None:
            result = cli_result
        else:
            # Step 3: API fallback — uses ANTHROPIC_API_KEY / OPENAI_API_KEY.
            logger.info("Falling back to %s API for analysis.", self.provider)
            system_prompt = self._load_system_prompt()

            user_prompt = f"## Story Context\n\n{story_context}\n"
            if module_summary:
                user_prompt += f"\n## Module Structure\n\n{module_summary}\n"
            user_prompt += "\nAnalyze this story and respond with the JSON output."

            # Fail fast if we're in a rate limit cooldown.
            from src.utils.rate_limit import check_cooldown
            cooldown_msg = check_cooldown(self.provider)
            if cooldown_msg:
                logger.warning("Skipping analysis: %s", cooldown_msg.split('\n')[0])
                return AnalysisResult(
                    summary=f"Analysis failed: {cooldown_msg.split(chr(10))[0]}",
                    raw_response=cooldown_msg,
                )

            try:
                response = self._call_ai(system_prompt, user_prompt)
                result = self._parse_response(response)
            except Exception as e:
                logger.error("AI analysis failed: %s", e)
                return AnalysisResult(
                    summary=f"Analysis failed: {e}",
                    raw_response=str(e),
                )

        # Safety net: SPIKE stories never require code changes.
        if "[spike]" in story_context.lower() and result.requires_code_change:
            logger.info("SPIKE story detected — overriding requires_code_change to False.")
            result.requires_code_change = False
            if not result.recommendation:
                result.recommendation = "Create implementation stories based on this spike analysis."

        return result

    def _python_heuristic(self, story_context: str) -> AnalysisResult | None:
        """Pure Python analysis — catches obvious cases without any AI call.

        Returns AnalysisResult for clear-cut cases, None if AI is needed.
        """
        ctx_lower = story_context.lower()

        # Extract description section.
        description = ""
        for line in story_context.splitlines():
            if line.startswith("## Description"):
                idx = story_context.index(line) + len(line)
                rest = story_context[idx:]
                end = rest.find("\n## ")
                description = (rest[:end].strip() if end > 0 else rest.strip())
                break

        # No description → flag low quality, let quality gate handle it.
        if not description or description.lower() in ("none", "none specified", "n/a", ""):
            return AnalysisResult(
                summary="Story has no description — cannot determine requirements.",
                requires_code_change=True,
                confidence="low",
                estimated_complexity="unknown",
                recommendation="Add a description with clear requirements before processing.",
            )

        # Non-code story detection.
        non_code_signals = [
            "investigate", "research", "discuss", "meeting", "documentation only",
            "no code change", "configuration change only", "environment setup",
            "deployment only", "review only", "spike", "proof of concept",
        ]
        code_signals = [
            "implement", "fix bug", "add feature", "create new", "modify the",
            "update the code", "change the", "refactor", "migrate", "add a new",
            "should return", "should display", "should handle", "add hook",
            "add function", "add method", "add endpoint", "fix the",
        ]

        non_code_hits = sum(1 for s in non_code_signals if s in ctx_lower)
        code_hits = sum(1 for s in code_signals if s in ctx_lower)

        if non_code_hits >= 2 and code_hits == 0:
            return AnalysisResult(
                summary=(
                    f"Story appears to be non-code (investigation/process). "
                    f"{non_code_hits} non-code signal(s), 0 code signals."
                ),
                requires_code_change=False,
                confidence="high",
                estimated_complexity="trivial",
                recommendation="This story does not require code changes. Review manually.",
            )

        # Can't determine confidently — needs AI.
        return None

    # --- URL fetching ---

    def _extract_and_fetch_urls(self, story_context: str) -> str:
        """Extract URLs from story context, fetch their content, return as markdown.

        Pure Python — no AI cost. Handles:
        - Public URLs: fetched directly.
        - Auth-protected URLs (401/403): prompts user for credentials interactively.
        - Timeouts / errors: logged and skipped gracefully.

        Returns a markdown section with fetched content, or empty string.
        """
        # Extract URLs (http/https only, skip Azure DevOps work item URLs).
        urls = re.findall(r'https?://[^\s<>"\)\]]+', story_context)
        # De-duplicate while preserving order.
        seen: set[str] = set()
        unique_urls: list[str] = []
        for url in urls:
            # Strip trailing punctuation that's not part of the URL.
            url = url.rstrip(".,;:!?)")
            if url not in seen and "_workitems/edit/" not in url:
                seen.add(url)
                unique_urls.append(url)

        if not unique_urls:
            return ""

        logger.info("Found %d URL(s) in story context: %s", len(unique_urls), unique_urls)

        sections: list[str] = []
        for url in unique_urls[:3]:  # Cap at 3 URLs to avoid bloating context.
            content = self._fetch_url(url)
            if content:
                # Truncate to keep context reasonable for Claude CLI.
                if len(content) > 8000:
                    content = content[:8000] + "\n\n... (content truncated at 8,000 chars)"
                sections.append(f"### Content from: {url}\n\n{content}")

        if not sections:
            return ""

        return "## Referenced Documents (auto-fetched)\n\n" + "\n\n".join(sections)

    def _fetch_url(self, url: str) -> str:
        """Fetch a single URL and return its text content.

        Special handling for known platforms:
        - Confluence/Atlassian Cloud: uses REST API with API token.
        - Other URLs: tries unauthenticated, prompts for creds on 401/403.
        Returns empty string on failure.
        """
        import sys

        import httpx

        # Confluence Cloud wiki pages → use REST API (browser URL returns JS login page).
        confluence_match = re.match(
            r'https://([^/]+)\.atlassian\.net/wiki/spaces/([^/]+)/pages/(\d+)',
            url,
        )
        if confluence_match:
            return self._fetch_confluence_page(
                domain=confluence_match.group(1),
                page_id=confluence_match.group(3),
                original_url=url,
            )

        headers = {
            "User-Agent": "DevOps-AI-Agent/1.0 (story-analyzer)",
            "Accept": "text/html, application/json, text/plain",
        }

        try:
            resp = httpx.get(url, headers=headers, timeout=15, follow_redirects=True)

            if resp.status_code in (401, 403):
                logger.info("URL requires authentication (HTTP %d): %s", resp.status_code, url)

                # Only prompt if running interactively.
                if not sys.stdin.isatty():
                    logger.warning("Non-interactive mode — skipping auth-protected URL.")
                    return ""

                return self._fetch_url_with_credentials(url, headers)

            if resp.status_code != 200:
                logger.warning("URL returned HTTP %d: %s", resp.status_code, url)
                return ""

            text = self._extract_text(resp.text, resp.headers.get("content-type", ""))

            # Detect Atlassian/Confluence login walls (200 + JS login page).
            if "atlassian" in url and ("JavaScript is disabled" in text or "Log in with Atlassian" in text):
                logger.info("Confluence login wall detected — trying REST API.")
                # Try to extract domain and page ID from URL.
                m = re.match(r'https://([^/]+)\.atlassian\.net/wiki/.*?/(\d+)', url)
                if m:
                    return self._fetch_confluence_page(m.group(1), m.group(2), url)
                # Generic auth prompt fallback.
                if sys.stdin.isatty():
                    return self._fetch_url_with_credentials(url, headers)
                return ""

            return text

        except httpx.TimeoutException:
            logger.warning("URL fetch timed out (15s): %s", url)
        except httpx.RequestError as e:
            logger.warning("URL fetch failed: %s — %s", url, e)
        except Exception as e:
            logger.warning("Unexpected error fetching URL %s: %s", url, e)

        return ""

    def _fetch_confluence_page(self, domain: str, page_id: str, original_url: str) -> str:
        """Fetch a Confluence Cloud page via REST API.

        Requires an Atlassian API token. Checks config first, then env var,
        then prompts interactively.
        """
        import os
        import sys

        import httpx

        # Look for credentials: config → env → interactive prompt.
        confluence_cfg = self.config.get("confluence", {})
        email = confluence_cfg.get("email") or os.environ.get("CONFLUENCE_EMAIL", "")
        token = confluence_cfg.get("api_token") or os.environ.get("CONFLUENCE_API_TOKEN", "")

        if not email or not token:
            if not sys.stdin.isatty():
                logger.warning("Confluence credentials not configured — skipping %s", original_url)
                return ""

            from rich.console import Console
            console = Console()
            console.print(f"\n[yellow]Confluence page requires authentication:[/] {original_url}")
            console.print("You need an Atlassian API token (https://id.atlassian.net/manage-profile/security/api-tokens)")
            console.print("[dim]Tip: set CONFLUENCE_EMAIL and CONFLUENCE_API_TOKEN env vars to skip this prompt.[/]")

            if not email:
                email = input("Atlassian email: ").strip()
            if not token:
                token = input("API token: ").strip()

            if not email or not token:
                return ""

        api_url = f"https://{domain}.atlassian.net/wiki/rest/api/content/{page_id}?expand=body.storage"

        try:
            resp = httpx.get(
                api_url,
                auth=httpx.BasicAuth(email, token),
                headers={"Accept": "application/json"},
                timeout=15,
            )

            if resp.status_code == 200:
                data = resp.json()
                title = data.get("title", "")
                html_body = data.get("body", {}).get("storage", {}).get("value", "")
                text = self._extract_text(html_body, "text/html")
                if title:
                    text = f"# {title}\n\n{text}"
                logger.info("Confluence page fetched: '%s' (%d chars)", title, len(text))
                return text
            elif resp.status_code in (401, 403):
                logger.warning("Confluence API auth failed (HTTP %d). Check email/token.", resp.status_code)
            else:
                logger.warning("Confluence API returned HTTP %d for page %s.", resp.status_code, page_id)

        except Exception as e:
            logger.warning("Confluence API fetch failed: %s", e)

        return ""

    def _fetch_url_with_credentials(self, url: str, headers: dict) -> str:
        """Prompt user for credentials and retry the URL fetch."""
        import httpx
        from rich.console import Console

        console = Console()
        console.print(f"\n[yellow]URL requires authentication:[/] {url}")
        console.print("Options: (1) Username/password  (2) Bearer token  (3) Cookie  (s) Skip")

        choice = input("Choice [1/2/3/s]: ").strip().lower()
        if choice == "s" or not choice:
            return ""

        auth = None
        extra_headers = dict(headers)

        if choice == "1":
            username = input("Username: ").strip()
            password = input("Password: ").strip()
            if not username:
                return ""
            auth = httpx.BasicAuth(username, password)
        elif choice == "2":
            token = input("Bearer token: ").strip()
            if not token:
                return ""
            extra_headers["Authorization"] = f"Bearer {token}"
        elif choice == "3":
            cookie = input("Cookie header value: ").strip()
            if not cookie:
                return ""
            extra_headers["Cookie"] = cookie
        else:
            return ""

        try:
            resp = httpx.get(
                url, headers=extra_headers, auth=auth,
                timeout=15, follow_redirects=True,
            )
            if resp.status_code == 200:
                logger.info("Authenticated fetch succeeded for %s", url)
                return self._extract_text(resp.text, resp.headers.get("content-type", ""))
            else:
                logger.warning("Authenticated fetch returned HTTP %d for %s", resp.status_code, url)
        except Exception as e:
            logger.warning("Authenticated fetch failed for %s: %s", url, e)

        return ""

    @staticmethod
    def _extract_text(body: str, content_type: str) -> str:
        """Extract readable text from an HTTP response body.

        Handles HTML (strips tags, extracts main content), JSON, and plain text.
        """
        ct = content_type.lower()

        if "json" in ct:
            # Return pretty-printed JSON.
            try:
                data = json.loads(body)
                return json.dumps(data, indent=2, ensure_ascii=False)
            except json.JSONDecodeError:
                return body[:8000]

        if "html" in ct:
            # Extract meaningful text from HTML.
            # Remove script/style blocks first.
            text = re.sub(r'<(script|style|nav|header|footer)[^>]*>.*?</\1>', '', body, flags=re.DOTALL | re.IGNORECASE)
            # Remove HTML tags.
            text = re.sub(r'<[^>]+>', ' ', text)
            # Collapse whitespace.
            text = re.sub(r'[ \t]+', ' ', text)
            text = re.sub(r'\n\s*\n+', '\n\n', text)
            # Decode HTML entities.
            import html
            text = html.unescape(text)
            return text.strip()

        # Plain text / other.
        return body.strip()

    def _try_claude_cli(self, story_context: str, module_summary: str = "") -> AnalysisResult | None:
        """Analyze via Claude Code CLI — uses Team plan, no API cost."""
        from src.agent.implement import _command_exists

        if not _command_exists("claude"):
            logger.debug("Claude Code CLI not available — skipping to API fallback.")
            return None

        system_prompt = self._load_system_prompt()
        prompt = f"{system_prompt}\n\n## Story Context\n\n{story_context}\n"
        if module_summary:
            prompt += f"\n## Module Structure\n\n{module_summary}\n"
        prompt += "\nAnalyze this story and respond with ONLY the JSON output."

        logger.info("Analyzing via Claude Code CLI (%d chars)...", len(prompt))

        try:
            result = subprocess.run(
                ["claude", "-p"],
                input=prompt,
                capture_output=True,
                text=True,
                timeout=300,
            )
            if result.returncode == 0 and result.stdout.strip():
                logger.info("Claude CLI analysis succeeded.")
                return self._parse_response(result.stdout)
            else:
                stderr = (result.stderr or "").strip()
                logger.warning(
                    "Claude CLI analysis failed (exit %d): %s",
                    result.returncode, stderr[:200],
                )
        except subprocess.TimeoutExpired:
            logger.warning("Claude CLI analysis timed out (300s).")
        except FileNotFoundError:
            logger.warning("Claude Code CLI not found in PATH.")

        return None

    def _call_ai(self, system_prompt: str, user_prompt: str) -> str:
        """Call the configured AI provider.

        Copilot provider retries up to 3 times with exponential backoff.
        """
        if self.provider == "anthropic":
            import anthropic

            anth = anthropic.Anthropic()
            try:
                msg = anth.messages.create(
                    model=self.model,
                    max_tokens=self.max_tokens,
                    temperature=self.temperature,
                    system=system_prompt,
                    messages=[{"role": "user", "content": user_prompt}],
                )
            except anthropic.RateLimitError as e:
                from ..utils.rate_limit import record_rate_limit
                record_rate_limit("anthropic", e)
                raise
            self._record_usage(msg, "analyze")
            return msg.content[0].text

        if self.provider == "copilot":
            from .implement import _get_github_token

            token = _get_github_token()
            client = openai.OpenAI(
                base_url="https://models.github.ai/inference/v1",
                api_key=token,
            )
        elif self.provider == "openai":
            client = openai.OpenAI()
        else:
            client = openai.OpenAI()

        import time

        last_error = None
        max_attempts = 1  # Fail fast — analysis is non-blocking in the pipeline.
        for attempt in range(max_attempts):
            try:
                resp = client.chat.completions.create(
                    model=self.model,
                    max_tokens=self.max_tokens,
                    temperature=self.temperature,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt},
                    ],
                )
                self._record_usage(resp, "analyze")
                return resp.choices[0].message.content
            except (openai.RateLimitError, openai.APIConnectionError, openai.APITimeoutError) as e:
                last_error = e
                wait = [5, 20, 60][attempt]
                logger.warning("Analysis API attempt %d failed (%s), retrying in %ds...", attempt + 1, type(e).__name__, wait)
                time.sleep(wait)
            except openai.AuthenticationError:
                raise RuntimeError(
                    "GitHub token rejected by Models API. Run `gh auth login` or check GITHUB_TOKEN."
                )

        if isinstance(last_error, openai.RateLimitError):
            from src.utils.rate_limit import record_rate_limit
            record_rate_limit(self.provider, last_error)
            raise RuntimeError(
                "\u23f3 Rate limit reached \u2014 analysis skipped. "
                "Use --skip-analysis to avoid this delay."
            )
        raise RuntimeError(f"Analysis API failed after {max_attempts} attempts: {last_error}")

    def _parse_response(self, response: str) -> AnalysisResult:
        """Parse JSON response from AI into AnalysisResult."""
        import re

        text = response.strip()
        # Extract JSON from markdown code fences (handles ```json, ```JSON, extra whitespace).
        fence_match = re.search(r'```(?:json)?\s*\n(.*?)```', text, re.DOTALL | re.IGNORECASE)
        if fence_match:
            text = fence_match.group(1).strip()
        elif text.startswith("```"):
            text = text.split("\n", 1)[1] if "\n" in text else text[3:]
            if text.endswith("```"):
                text = text[:-3]
            text = text.strip()

        try:
            data = json.loads(text)
        except json.JSONDecodeError:
            # Try to find a JSON object anywhere in the response (handles preamble text).
            json_match = re.search(r'\{[^{}]*"summary"[^{}]*\}', text, re.DOTALL)
            if not json_match:
                # Try to find a partial JSON that starts with { but is truncated.
                json_match = re.search(r'(\{.*"summary"\s*:\s*"[^"]*".*)', text, re.DOTALL)
            if json_match:
                try:
                    data = json.loads(json_match.group(0))
                except json.JSONDecodeError:
                    # Partial JSON — extract what we can with regex.
                    data = self._extract_fields_from_partial_json(json_match.group(0))
                    if not data:
                        logger.warning("Could not parse AI response as JSON, using raw text.")
                        return AnalysisResult(summary=text[:500], raw_response=response)
            else:
                logger.warning("Could not parse AI response as JSON, using raw text.")
                return AnalysisResult(summary=text[:500], raw_response=response)

        return AnalysisResult(
            summary=data.get("summary", ""),
            requires_code_change=data.get("requires_code_change", True),
            confidence=data.get("confidence", "medium"),
            affected_areas=data.get("affected_areas", []),
            approach=data.get("approach", ""),
            risks=data.get("risks", []),
            questions=data.get("questions", []),
            estimated_complexity=data.get("estimated_complexity", "moderate"),
            recommendation=data.get("recommendation", ""),
            raw_response=response,
        )

    def _extract_fields_from_partial_json(self, text: str) -> dict | None:
        """Extract fields from truncated JSON using regex."""
        import re

        fields: dict = {}

        # Extract string fields.
        for key in ("summary", "approach", "confidence", "estimated_complexity", "recommendation"):
            m = re.search(rf'"{key}"\s*:\s*"((?:[^"\\]|\\.)*)"', text, re.DOTALL)
            if m:
                fields[key] = m.group(1).replace('\\"', '"').replace('\\n', '\n')

        # Extract boolean.
        m = re.search(r'"requires_code_change"\s*:\s*(true|false)', text, re.IGNORECASE)
        if m:
            fields["requires_code_change"] = m.group(1).lower() == "true"

        # Extract arrays (best effort).
        for key in ("affected_areas", "risks", "questions"):
            m = re.search(rf'"{key}"\s*:\s*\[(.*?)\]', text, re.DOTALL)
            if m:
                items = re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(1))
                fields[key] = items

        return fields if fields.get("summary") else None

    def _load_system_prompt(self) -> str:
        """Load the analysis system prompt template."""
        if _TEMPLATE_PATH.exists():
            return _TEMPLATE_PATH.read_text()
        return "Analyze the story and respond with a JSON analysis."
