"""AI story analyzer — analyzes work items before implementation."""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path

import openai

logger = logging.getLogger("devops_ai_agent.analyzer")

_TEMPLATE_PATH = Path(__file__).parent.parent.parent / "templates" / "analyze.md"


@dataclass
class AnalysisResult:
    """Structured result from AI story analysis."""

    summary: str = ""
    requires_code_change: bool = True
    confidence: str = "medium"
    affected_areas: list[str] = field(default_factory=list)
    approach: str = ""
    risks: list[str] = field(default_factory=list)
    questions: list[str] = field(default_factory=list)
    estimated_complexity: str = "moderate"
    recommendation: str = ""
    raw_response: str = ""

    def to_markdown(self) -> str:
        """Format the analysis as a markdown comment for Azure DevOps / Zendesk."""
        code_label = "Yes" if self.requires_code_change else "No"
        areas = ", ".join(self.affected_areas) if self.affected_areas else "N/A"
        risks = "\n".join(f"- {r}" for r in self.risks) if self.risks else "- None identified"
        questions = "\n".join(f"- {q}" for q in self.questions) if self.questions else "- None"

        return (
            f"## 🤖 AI Story Analysis\n\n"
            f"**Summary:** {self.summary}\n\n"
            f"| Attribute | Value |\n"
            f"|-----------|-------|\n"
            f"| Code change required | {code_label} |\n"
            f"| Confidence | {self.confidence} |\n"
            f"| Complexity | {self.estimated_complexity} |\n"
            f"| Affected areas | {areas} |\n\n"
            f"### Approach\n{self.approach}\n\n"
            f"### Risks\n{risks}\n\n"
            f"### Open Questions\n{questions}\n\n"
            f"### Recommendation\n{self.recommendation}\n\n"
            f"---\n*Generated by DevOps AI Agent*"
        )


class StoryAnalyzer:
    """Analyzes stories/tickets using AI to determine next steps."""

    def __init__(self, config: dict):
        self.config = config
        ai = config.get("ai_agent", {})
        self.provider = ai.get("provider", "copilot")
        self.model = ai.get("model", "gpt-4o")
        self.max_tokens = ai.get("max_tokens", 4096)
        self.temperature = ai.get("temperature", 0.2)
        self.story_id: int | None = None  # Set by pipeline before calling analyze()

    def _record_usage(self, response, stage: str) -> None:
        """Record token usage from an API response."""
        try:
            from src.history import save_token_usage
            usage = getattr(response, "usage", None)
            if not usage:
                return
            prompt = getattr(usage, "prompt_tokens", 0) or getattr(usage, "input_tokens", 0) or 0
            completion = getattr(usage, "completion_tokens", 0) or getattr(usage, "output_tokens", 0) or 0
            save_token_usage(
                story_id=self.story_id, stage=stage, provider=self.provider,
                model=self.model, prompt_tokens=prompt, completion_tokens=completion,
            )
        except Exception as e:
            logger.debug("Failed to record token usage: %s", e)

    def analyze(self, story_context: str, module_summary: str = "") -> AnalysisResult:
        """Analyze a story and return structured findings."""
        system_prompt = self._load_system_prompt()

        user_prompt = f"## Story Context\n\n{story_context}\n"
        if module_summary:
            user_prompt += f"\n## Module Structure\n\n{module_summary}\n"
        user_prompt += "\nAnalyze this story and respond with the JSON output."

        logger.info("Analyzing story via %s/%s...", self.provider, self.model)

        # Fail fast if we're in a rate limit cooldown.
        from src.utils.rate_limit import check_cooldown
        cooldown_msg = check_cooldown(self.provider)
        if cooldown_msg:
            logger.warning("Skipping analysis: %s", cooldown_msg.split('\n')[0])
            return AnalysisResult(
                summary=f"Analysis failed: {cooldown_msg.split(chr(10))[0]}",
                raw_response=cooldown_msg,
            )

        try:
            response = self._call_ai(system_prompt, user_prompt)
            return self._parse_response(response)
        except Exception as e:
            logger.error("AI analysis failed: %s", e)
            return AnalysisResult(
                summary=f"Analysis failed: {e}",
                raw_response=str(e),
            )

    def _call_ai(self, system_prompt: str, user_prompt: str) -> str:
        """Call the configured AI provider.

        Copilot provider retries up to 3 times with exponential backoff.
        """
        if self.provider == "anthropic":
            import anthropic

            anth = anthropic.Anthropic()
            try:
                msg = anth.messages.create(
                    model=self.model,
                    max_tokens=self.max_tokens,
                    temperature=self.temperature,
                    system=system_prompt,
                    messages=[{"role": "user", "content": user_prompt}],
                )
            except anthropic.RateLimitError as e:
                from ..utils.rate_limit import record_rate_limit
                record_rate_limit("anthropic", e)
                raise
            self._record_usage(msg, "analyze")
            return msg.content[0].text

        if self.provider == "copilot":
            from .implement import _get_github_token

            token = _get_github_token()
            client = openai.OpenAI(
                base_url="https://models.github.ai/inference/v1",
                api_key=token,
            )
        elif self.provider == "openai":
            client = openai.OpenAI()
        else:
            client = openai.OpenAI()

        import time

        last_error = None
        max_attempts = 1  # Fail fast — analysis is non-blocking in the pipeline.
        for attempt in range(max_attempts):
            try:
                resp = client.chat.completions.create(
                    model=self.model,
                    max_tokens=self.max_tokens,
                    temperature=self.temperature,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt},
                    ],
                )
                self._record_usage(resp, "analyze")
                return resp.choices[0].message.content
            except (openai.RateLimitError, openai.APIConnectionError, openai.APITimeoutError) as e:
                last_error = e
                wait = [5, 20, 60][attempt]
                logger.warning("Analysis API attempt %d failed (%s), retrying in %ds...", attempt + 1, type(e).__name__, wait)
                time.sleep(wait)
            except openai.AuthenticationError:
                raise RuntimeError(
                    "GitHub token rejected by Models API. Run `gh auth login` or check GITHUB_TOKEN."
                )

        if isinstance(last_error, openai.RateLimitError):
            from src.utils.rate_limit import record_rate_limit
            record_rate_limit(self.provider, last_error)
            raise RuntimeError(
                "\u23f3 Rate limit reached \u2014 analysis skipped. "
                "Use --skip-analysis to avoid this delay."
            )
        raise RuntimeError(f"Analysis API failed after {max_attempts} attempts: {last_error}")

    def _parse_response(self, response: str) -> AnalysisResult:
        """Parse JSON response from AI into AnalysisResult."""
        import re

        text = response.strip()
        # Extract JSON from markdown code fences (handles ```json, ```JSON, extra whitespace).
        fence_match = re.search(r'```(?:json)?\s*\n(.*?)```', text, re.DOTALL | re.IGNORECASE)
        if fence_match:
            text = fence_match.group(1).strip()
        elif text.startswith("```"):
            text = text.split("\n", 1)[1] if "\n" in text else text[3:]
            if text.endswith("```"):
                text = text[:-3]
            text = text.strip()

        try:
            data = json.loads(text)
        except json.JSONDecodeError:
            logger.warning("Could not parse AI response as JSON, using raw text.")
            return AnalysisResult(summary=text[:500], raw_response=response)

        return AnalysisResult(
            summary=data.get("summary", ""),
            requires_code_change=data.get("requires_code_change", True),
            confidence=data.get("confidence", "medium"),
            affected_areas=data.get("affected_areas", []),
            approach=data.get("approach", ""),
            risks=data.get("risks", []),
            questions=data.get("questions", []),
            estimated_complexity=data.get("estimated_complexity", "moderate"),
            recommendation=data.get("recommendation", ""),
            raw_response=response,
        )

    def _load_system_prompt(self) -> str:
        """Load the analysis system prompt template."""
        if _TEMPLATE_PATH.exists():
            return _TEMPLATE_PATH.read_text()
        return "Analyze the story and respond with a JSON analysis."
