"""Context builder — assembles the full story context for the AI agent."""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from src.integrations.azure_devops import WorkItem

logger = logging.getLogger("devops_ai_agent.context")

CONTEXT_FILENAME = ".current-story.md"
RUN_HISTORY_FILENAME = ".pipeline-history.json"

# Pipeline metadata is stored in the devops-ai-agent project directory,
# NOT in the target workspace. This avoids polluting the target repo
# with untracked files that block git checkouts.
_DATA_DIR = Path(__file__).resolve().parent.parent.parent / ".dai"


def _ensure_data_dir() -> Path:
    """Ensure the .dai/ data directory exists."""
    _DATA_DIR.mkdir(parents=True, exist_ok=True)
    return _DATA_DIR


def _build_comments_section(comments: list[dict[str, str]]) -> str:
    """Build the comments markdown, filtering out pipeline-generated noise.

    - Skips comments containing the pipeline signature (AI already gets this via history_ctx).
    - Includes human comments newest-first, capped at _MAX_COMMENTS_CHARS.
    """
    if not comments:
        return "No comments yet.\n"

    # Filter out pipeline-generated comments.
    human_comments = [
        c for c in comments
        if _PIPELINE_SIGNATURE not in c.get("text", "")
    ]

    if not human_comments:
        return "No human comments (pipeline-generated comments filtered).\n"

    # Include newest-first, capped at budget.
    result = ""
    total = len(human_comments)
    included = 0
    for c in reversed(human_comments):
        entry = f"### {c['date']}\n{c['text']}\n\n"
        if len(result) + len(entry) > _MAX_COMMENTS_CHARS:
            break
        result += entry
        included += 1

    omitted = total - included
    if omitted > 0:
        result += f"*({omitted} older comment(s) omitted)*\n"

    return result


_PIPELINE_SIGNATURE = "Generated by DevOps AI Agent"
_MAX_COMMENTS_CHARS = 2000


def build_story_context(work_item: WorkItem, config: dict) -> str:
    """Build a markdown context document from a work item."""
    comments_md = _build_comments_section(work_item.comments)

    module_path = config["project"].get("module_path", "")
    project_name = config["project"].get("name", "")
    local_env = config.get("local_env", {})
    cli_prefix = local_env.get("drush_prefix", local_env.get("cli_prefix", ""))

    # Build framework-specific dev notes from profile.
    from src.profiles import get_profile
    profile = get_profile(config)
    dev_notes = profile["dev_notes"].replace("{cli_prefix}", cli_prefix) if cli_prefix else profile["dev_notes"]

    context = f"""# Current Work Item

- **ID:** {work_item.id}
- **Type:** {work_item.work_item_type}
- **Title:** {work_item.title}
- **State:** {work_item.state}
- **Tags:** {work_item.tags}
- **URL:** {work_item.url}

## Description

{work_item.description}

## Acceptance Criteria

{work_item.acceptance_criteria}

## Discussion / Comments

{comments_md}

## Development Notes

- Project: {project_name}
- Module path: {module_path}
- Framework: {profile['framework_label']} ({profile['language']} {profile['language_version']})
{dev_notes}
"""
    return context


def save_story_context(work_item: WorkItem, config: dict) -> Path:
    """Save the story context to the data directory."""
    data_dir = _ensure_data_dir()
    context_file = data_dir / CONTEXT_FILENAME
    content = build_story_context(work_item, config)
    context_file.write_text(content)
    logger.info("Story context saved to %s", context_file)
    return context_file


def load_story_context(config: dict) -> str | None:
    """Load existing story context from data directory."""
    context_file = _DATA_DIR / CONTEXT_FILENAME
    if context_file.exists():
        return context_file.read_text()
    return None


# --- Run history (persists across pipeline runs) ---

def _history_path(config: dict) -> Path:
    data_dir = _ensure_data_dir()
    return data_dir / RUN_HISTORY_FILENAME


def load_run_history(config: dict) -> list[dict]:
    """Load previous pipeline run records."""
    path = _history_path(config)
    if path.exists():
        try:
            return json.loads(path.read_text())
        except (json.JSONDecodeError, OSError):
            return []
    return []


def save_run_record(config: dict, record: dict) -> None:
    """Append a run record to the history file. Keeps last 10 runs."""
    history = load_run_history(config)
    record["timestamp"] = datetime.now(timezone.utc).isoformat()
    history.append(record)
    history = history[-10:]  # keep last 10
    _history_path(config).write_text(json.dumps(history, indent=2))
    logger.info("Run record saved (%d total).", len(history))


def build_history_context(config: dict, work_item_id: int) -> str:
    """Build a markdown section summarizing previous runs for the same story."""
    history = load_run_history(config)
    relevant = [r for r in history if r.get("work_item_id") == work_item_id]
    if not relevant:
        return ""

    lines = ["## Previous Run History\n"]
    for i, run in enumerate(relevant, 1):
        ts = run.get("timestamp", "unknown")
        failed_stage = run.get("failed_stage", "none")
        error = run.get("error", "")
        method = run.get("method", "")
        lines.append(f"### Run {i} ({ts})")
        lines.append(f"- **Result:** {'FAILED at ' + failed_stage if failed_stage else 'SUCCESS'}")
        if method:
            lines.append(f"- **Method:** {method}")
        if error:
            lines.append(f"- **Error:** {error[:500]}")
        ai_output = run.get("ai_output", "")
        if ai_output:
            lines.append(f"- **AI output preview:** {ai_output[:300]}")
        lines.append("")

    lines.append(
        "> Use the above history to avoid repeating mistakes. "
        "If a previous approach failed, try a different strategy.\n"
    )
    return "\n".join(lines)
